/*
=============================================================================
SQL SCHEMA SETUP — Content Engagement Analytics Platform
=============================================================================
Run this script FIRST before loading any data or running any analysis queries.

Steps performed:
  1. Create the database (optional — skip if already exists)
  2. Create tables: play_events, content_catalogue
  3. Create indexes for query performance
  4. Load data via COPY command (adjust paths to your local file location)
  5. Run post-load validation

PostgreSQL version: 13+
=============================================================================
*/

-- ── 0. Optional: Create a dedicated database ─────────────────────────────
-- Run this block as superuser (postgres) if starting fresh:
--
--   CREATE DATABASE content_analytics
--       WITH ENCODING = 'UTF8'
--            LC_COLLATE = 'en_US.utf8'
--            LC_CTYPE   = 'en_US.utf8';
--
--   \c content_analytics
-- ─────────────────────────────────────────────────────────────────────────

-- ── 1. Drop and recreate tables (idempotent setup) ────────────────────────
DROP TABLE IF EXISTS play_events CASCADE;
DROP TABLE IF EXISTS content_catalogue CASCADE;

-- ── 2. Content Catalogue Table ────────────────────────────────────────────
CREATE TABLE content_catalogue (
    content_id          VARCHAR(20)  NOT NULL,
    title               VARCHAR(500),            -- Allow long titles
    genre               VARCHAR(100),
    content_duration    INTEGER,                 -- Minutes
    release_date        DATE,

    CONSTRAINT pk_content_catalogue PRIMARY KEY (content_id)
);

COMMENT ON TABLE content_catalogue IS
    'Reference dimension table: one row per unique piece of content. '
    'Maps content_id to human-readable title, genre, and duration metadata.';

-- ── 3. Play Events Table (500,000 rows) ───────────────────────────────────
CREATE TABLE play_events (
    event_id                  VARCHAR(15)  NOT NULL,
    user_id                   VARCHAR(12)  NOT NULL,
    content_id                VARCHAR(20)  NOT NULL,
    watch_date                DATE         NOT NULL,
    watch_duration_minutes    INTEGER      NOT NULL,
    content_duration_minutes  INTEGER      NOT NULL,
    rewatch_flag              SMALLINT     NOT NULL DEFAULT 0,
    shared_flag               SMALLINT     NOT NULL DEFAULT 0,
    device_type               VARCHAR(30),
    user_age_group            VARCHAR(10),
    user_region               VARCHAR(50),
    genre                     VARCHAR(100),

    CONSTRAINT pk_play_events        PRIMARY KEY (event_id),
    CONSTRAINT fk_content            FOREIGN KEY (content_id)
                                         REFERENCES content_catalogue(content_id),
    CONSTRAINT chk_rewatch_flag      CHECK (rewatch_flag IN (0, 1)),
    CONSTRAINT chk_shared_flag       CHECK (shared_flag  IN (0, 1)),
    CONSTRAINT chk_watch_duration    CHECK (watch_duration_minutes > 0),
    CONSTRAINT chk_content_duration  CHECK (content_duration_minutes > 0)
);

COMMENT ON TABLE play_events IS
    'Fact table: one row per streaming play event. '
    '500,000 rows covering 2,000 users × 500 titles × Jan 2023 – Dec 2024. '
    'Source: generated by data/generate_play_events.py using beta-distributed watch durations.';

COMMENT ON COLUMN play_events.rewatch_flag IS
    '1 if the user had previously watched this title; 0 otherwise. '
    'Overall rate: ~8% (higher for >85% completion events).';

COMMENT ON COLUMN play_events.shared_flag IS
    '1 if the user shared this content after watching; 0 otherwise. '
    'Overall rate: ~4–7% depending on genre.';

-- ── 4. Performance Indexes ────────────────────────────────────────────────
-- These indexes are essential for analytical query performance on 500K rows.

-- Query 1 & 5: Engagement score aggregation per content
CREATE INDEX idx_pe_content_id
    ON play_events (content_id);

-- Query 2: Decay curve (content × date combinations)
CREATE INDEX idx_pe_content_date
    ON play_events (content_id, watch_date);

-- Query 3: Audience segment cross-tab (genre × age × device)
CREATE INDEX idx_pe_segment
    ON play_events (genre, user_age_group, device_type);

-- Query 4: Cold start analysis (date filtering per content)
CREATE INDEX idx_pe_date
    ON play_events (watch_date);

-- General analytics: user-level queries
CREATE INDEX idx_pe_user_id
    ON play_events (user_id);

-- Partial index for rewatch events only (faster rewatch-rate queries)
CREATE INDEX idx_pe_rewatch
    ON play_events (content_id, watch_date)
    WHERE rewatch_flag = 1;

-- Partial index for share events only
CREATE INDEX idx_pe_shared
    ON play_events (content_id, watch_date)
    WHERE shared_flag = 1;

-- ── 5. Load Data via COPY ─────────────────────────────────────────────────
-- Adjust the file paths to match your local environment.
-- On Windows: use forward slashes or escape backslashes.
-- IMPORTANT: Load content_catalogue FIRST (FK constraint).

/*
-- Load content catalogue (run as superuser or use \copy for non-superusers):
COPY content_catalogue (content_id, genre, content_duration, release_date)
FROM '/absolute/path/to/content-engagement-analytics/data/content_catalogue.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- If your content_catalogue.csv has a 'title' column (from netflix_titles.csv enrichment):
-- COPY content_catalogue (content_id, title, genre, content_duration, release_date)
-- FROM '/absolute/path/to/content_catalogue.csv'
-- WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- Load play events (larger file — ~47 MB, may take 15–30 seconds):
COPY play_events (
    event_id, user_id, content_id, watch_date,
    watch_duration_minutes, content_duration_minutes,
    rewatch_flag, shared_flag, device_type,
    user_age_group, user_region, genre
)
FROM '/absolute/path/to/content-engagement-analytics/data/play_events.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');
*/

-- If you cannot use COPY (no superuser access), use psql \copy instead:
-- \copy play_events FROM 'play_events.csv' CSV HEADER

-- ── 6. Post-Load Validation Queries ──────────────────────────────────────
-- Run these after loading to confirm data integrity.

-- 6a. Row counts
SELECT 'play_events'      AS table_name, COUNT(*) AS row_count FROM play_events
UNION ALL
SELECT 'content_catalogue',               COUNT(*)              FROM content_catalogue;
-- Expected: 500,000 | 500

-- 6b. Null check
SELECT
    SUM(CASE WHEN event_id                 IS NULL THEN 1 ELSE 0 END) AS null_event_id,
    SUM(CASE WHEN user_id                  IS NULL THEN 1 ELSE 0 END) AS null_user_id,
    SUM(CASE WHEN content_id              IS NULL THEN 1 ELSE 0 END) AS null_content_id,
    SUM(CASE WHEN watch_date              IS NULL THEN 1 ELSE 0 END) AS null_watch_date,
    SUM(CASE WHEN watch_duration_minutes  IS NULL THEN 1 ELSE 0 END) AS null_watch_dur,
    SUM(CASE WHEN content_duration_minutes IS NULL THEN 1 ELSE 0 END) AS null_content_dur
FROM play_events;
-- Expected: All zeros

-- 6c. Key distribution checks
SELECT
    COUNT(DISTINCT user_id)    AS unique_users,       -- Expected: ~2,000
    COUNT(DISTINCT content_id) AS unique_content,     -- Expected: 500
    MIN(watch_date)            AS earliest_event,     -- Expected: 2023-01-01
    MAX(watch_date)            AS latest_event,       -- Expected: 2024-12-31
    ROUND(AVG(rewatch_flag::NUMERIC) * 100, 2) AS rewatch_rate_pct,  -- Expected: ~8%
    ROUND(AVG(shared_flag::NUMERIC)  * 100, 2) AS share_rate_pct     -- Expected: ~4-5%
FROM play_events;

-- 6d. FK integrity check
SELECT COUNT(*) AS orphaned_events
FROM play_events pe
LEFT JOIN content_catalogue cc ON cc.content_id = pe.content_id
WHERE cc.content_id IS NULL;
-- Expected: 0

-- ── 7. Useful Analysis Helper View ───────────────────────────────────────
-- Pre-compute completion_pct to avoid repeating the LEAST(...) expression
-- in every analysis query.

CREATE OR REPLACE VIEW vw_play_events_enriched AS
SELECT
    pe.*,
    cc.title,
    cc.release_date,

    -- Completion fraction (capped at 1.0)
    LEAST(
        pe.watch_duration_minutes::NUMERIC / NULLIF(pe.content_duration_minutes, 0),
        1.0
    )                                               AS completion_fraction,

    -- Days since release (for decay analysis)
    (pe.watch_date - cc.release_date)               AS days_since_release,

    -- Watch date parts (for time-series analysis)
    DATE_TRUNC('week',  pe.watch_date)              AS week_start,
    DATE_TRUNC('month', pe.watch_date)              AS month_start,
    EXTRACT(YEAR  FROM pe.watch_date)::INTEGER      AS watch_year,
    EXTRACT(MONTH FROM pe.watch_date)::INTEGER      AS watch_month,
    EXTRACT(DOW   FROM pe.watch_date)::INTEGER      AS day_of_week   -- 0=Sun, 6=Sat

FROM play_events pe
LEFT JOIN content_catalogue cc ON cc.content_id = pe.content_id;

COMMENT ON VIEW vw_play_events_enriched IS
    'Enriched play events view joining content metadata and pre-computing '
    'completion fraction and date dimensions. Use this view in lieu of '
    'the raw play_events table for all analytical queries to reduce repetition.';

-- ── Done ─────────────────────────────────────────────────────────────────
SELECT 'Schema setup complete. Ready to run analysis queries 01–05.' AS status;
